name: CI
run-name: ${{github.actor}} commit ${{github.sha}}
on: [push]

jobs:
  ci-build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test